apiVersion: v1
kind: Pod
metadata:
  name: crash-loop
  namespace: k8sgpt-test
spec:
  containers:
  - name: stress-test
    image: polinux/stress # 包含了 stress-ng 工具的镜像
    resources:
      limits:
        memory: "50Mi"
        cpu: "1"
      requests:
        memory: "50Mi"
        cpu: "1"
    command: ["sh", "-c", "apt-get update && apt-get install -y stress-ng && stress-ng --vm 1 --vm-bytes 60M --vm-keep -m 1"]
 