apiVersion: v1
kind: Pod
metadata:
  name: dns-error
  namespace: k8sgpt-test
spec:
  dnsConfig:
    options:
    - name: ndots
      value: "100"
  containers:
  - name: nginx
    image: nginx:latest
