apiVersion: v1
kind: Pod
metadata:
  name: k8s-test-3
  labels:
    app: network-test
spec:
  containers:
  - name: network-test-container
    image: busybox
    command: ["/bin/sh", "-c"]
    args: ["while true; do wget -q --spider http://www.google.com; if [ $? -eq 0 ]; then echo 'Internet is up'; else echo 'Internet is down'; exit 1; fi; sleep 10; done"]
  restartPolicy: OnFailure
