apiVersion: v1
kind: Pod
metadata:
  name: k8s-test-1
spec:
  containers:
  - name: nginx
    image: nginx:latest
    volumeMounts:
    - name: config-volume
      mountPath: /etc/config
  volumes:
  - name: config-volume
    configMap:
      name: missing-configmap # 指向不存在的 ConfigMap
